// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

public class BookingResponse {
    private Long id;
    // Customer info
    private Long customerId;
    private String customerCode;
    private String customerName;
    private String customerPhone;
    // Pet info
    private Long petId;
    private String petName;
    private String petSpecies;
    private String petBreed;
    // Service info
    private Long serviceId;
    private String serviceName;
    private Integer durationMinutes;
    // Employee info
    private Long employeeId;
    private String employeeName;
    private LocalDateTime bookingDate;
    private LocalTime bookingTime;
    private Long orderId;
    // Pending | Confirmed | InProgress | Completed | Cancelled | NoShow
    private String status;
    private BigDecimal totalPrice;
    private String notes;
    private String cancellationReason;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCustomerId() {
        return this.customerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomerCode() {
        return this.customerCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomerName() {
        return this.customerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomerPhone() {
        return this.customerPhone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getPetId() {
        return this.petId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPetName() {
        return this.petName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPetSpecies() {
        return this.petSpecies;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPetBreed() {
        return this.petBreed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getServiceId() {
        return this.serviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getServiceName() {
        return this.serviceName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDurationMinutes() {
        return this.durationMinutes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getEmployeeId() {
        return this.employeeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmployeeName() {
        return this.employeeName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getBookingDate() {
        return this.bookingDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalTime getBookingTime() {
        return this.bookingTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCancellationReason() {
        return this.cancellationReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerId(final Long customerId) {
        this.customerId = customerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerCode(final String customerCode) {
        this.customerCode = customerCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerName(final String customerName) {
        this.customerName = customerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerPhone(final String customerPhone) {
        this.customerPhone = customerPhone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPetId(final Long petId) {
        this.petId = petId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPetName(final String petName) {
        this.petName = petName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPetSpecies(final String petSpecies) {
        this.petSpecies = petSpecies;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPetBreed(final String petBreed) {
        this.petBreed = petBreed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setServiceId(final Long serviceId) {
        this.serviceId = serviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setServiceName(final String serviceName) {
        this.serviceName = serviceName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDurationMinutes(final Integer durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmployeeId(final Long employeeId) {
        this.employeeId = employeeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmployeeName(final String employeeName) {
        this.employeeName = employeeName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBookingDate(final LocalDateTime bookingDate) {
        this.bookingDate = bookingDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBookingTime(final LocalTime bookingTime) {
        this.bookingTime = bookingTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderId(final Long orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalPrice(final BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCancellationReason(final String cancellationReason) {
        this.cancellationReason = cancellationReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
