// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import jakarta.validation.constraints.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class EmployeeDTO {
    private Long id;
    @NotBlank(message = "Tên không được để trống")
    private String fullName;
    @Email(message = "Email không hợp lệ")
    @NotBlank(message = "Email không được để trống")
    private String email;
    private String phone;
    @NotBlank(message = "Chức vụ không được để trống")
    private String position;
    @PositiveOrZero(message = "Lương phải >= 0")
    private BigDecimal salary;
    private LocalDateTime createdAt;
    private LocalDate hireDate;
    private String status;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class EmployeeDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String fullName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String email;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String phone;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String position;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal salary;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDate hireDate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        EmployeeDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder fullName(final String fullName) {
            this.fullName = fullName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder phone(final String phone) {
            this.phone = phone;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder position(final String position) {
            this.position = position;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder salary(final BigDecimal salary) {
            this.salary = salary;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder hireDate(final LocalDate hireDate) {
            this.hireDate = hireDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO.EmployeeDTOBuilder status(final String status) {
            this.status = status;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public EmployeeDTO build() {
            return new EmployeeDTO(this.id, this.fullName, this.email, this.phone, this.position, this.salary, this.createdAt, this.hireDate, this.status);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "EmployeeDTO.EmployeeDTOBuilder(id=" + this.id + ", fullName=" + this.fullName + ", email=" + this.email + ", phone=" + this.phone + ", position=" + this.position + ", salary=" + this.salary + ", createdAt=" + this.createdAt + ", hireDate=" + this.hireDate + ", status=" + this.status + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static EmployeeDTO.EmployeeDTOBuilder builder() {
        return new EmployeeDTO.EmployeeDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPosition() {
        return this.position;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getSalary() {
        return this.salary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getHireDate() {
        return this.hireDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPosition(final String position) {
        this.position = position;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSalary(final BigDecimal salary) {
        this.salary = salary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHireDate(final LocalDate hireDate) {
        this.hireDate = hireDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EmployeeDTO)) return false;
        final EmployeeDTO other = (EmployeeDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$fullName = this.getFullName();
        final java.lang.Object other$fullName = other.getFullName();
        if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        final java.lang.Object this$position = this.getPosition();
        final java.lang.Object other$position = other.getPosition();
        if (this$position == null ? other$position != null : !this$position.equals(other$position)) return false;
        final java.lang.Object this$salary = this.getSalary();
        final java.lang.Object other$salary = other.getSalary();
        if (this$salary == null ? other$salary != null : !this$salary.equals(other$salary)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$hireDate = this.getHireDate();
        final java.lang.Object other$hireDate = other.getHireDate();
        if (this$hireDate == null ? other$hireDate != null : !this$hireDate.equals(other$hireDate)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EmployeeDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $fullName = this.getFullName();
        result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        final java.lang.Object $position = this.getPosition();
        result = result * PRIME + ($position == null ? 43 : $position.hashCode());
        final java.lang.Object $salary = this.getSalary();
        result = result * PRIME + ($salary == null ? 43 : $salary.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $hireDate = this.getHireDate();
        result = result * PRIME + ($hireDate == null ? 43 : $hireDate.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "EmployeeDTO(id=" + this.getId() + ", fullName=" + this.getFullName() + ", email=" + this.getEmail() + ", phone=" + this.getPhone() + ", position=" + this.getPosition() + ", salary=" + this.getSalary() + ", createdAt=" + this.getCreatedAt() + ", hireDate=" + this.getHireDate() + ", status=" + this.getStatus() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public EmployeeDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public EmployeeDTO(final Long id, final String fullName, final String email, final String phone, final String position, final BigDecimal salary, final LocalDateTime createdAt, final LocalDate hireDate, final String status) {
        this.id = id;
        this.fullName = fullName;
        this.email = email;
        this.phone = phone;
        this.position = position;
        this.salary = salary;
        this.createdAt = createdAt;
        this.hireDate = hireDate;
        this.status = status;
    }
}
