// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.List;

public class OrderRequest {
    @NotNull(message = "CustomerID không được trống")
    private Long customerId;
    // Có thể để null nếu không giảm giá
    private BigDecimal discountAmount = BigDecimal.ZERO;
    private String notes;
    // Tổng tiền dịch vụ — frontend tính và gửi lên
    // Backend cộng vào totalAmount cùng với product items
    private BigDecimal serviceAmount = BigDecimal.ZERO;
    // items có thể rỗng nếu chỉ đặt dịch vụ
    @Valid
    private List<OrderItemRequest> items;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCustomerId() {
        return this.customerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getServiceAmount() {
        return this.serviceAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<OrderItemRequest> getItems() {
        return this.items;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerId(final Long customerId) {
        this.customerId = customerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiscountAmount(final BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setServiceAmount(final BigDecimal serviceAmount) {
        this.serviceAmount = serviceAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setItems(final List<OrderItemRequest> items) {
        this.items = items;
    }
}
