// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import java.math.BigDecimal;

public class OrderDetailResponse {
    private Long orderDetailId;
    private Long productId;
    private String productName;
    private Integer quantity;
    private BigDecimal unitPrice;
    private BigDecimal subtotal;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getOrderDetailId() {
        return this.orderDetailId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getProductId() {
        return this.productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getProductName() {
        return this.productName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderDetailId(final Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProductId(final Long productId) {
        this.productId = productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProductName(final String productName) {
        this.productName = productName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUnitPrice(final BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubtotal(final BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
}
