// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import com.petshop.backend.dto.ServiceItemResponse;

public class OrderResponse {
    private Long orderId;
    // Thông tin Customer
    private Long customerId;
    private String customerCode;
    private String customerName;
    private String customerPhone;
    // Thông tin đơn hàng
    private LocalDateTime orderDate;
    private BigDecimal totalAmount;
    private BigDecimal discountAmount;
    private BigDecimal finalAmount;
    private String status;
    private String notes;
    private LocalDateTime createdAt;
    // Chi tiết sản phẩm
    private List<OrderDetailResponse> items;
    // Chi tiết dịch vụ (parse từ notes)
    private List<ServiceItemResponse> serviceItems;
    // Thông tin thanh toán (nếu đã thanh toán)
    private String paymentStatus;
    private String paymentMethod;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCustomerId() {
        return this.customerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomerCode() {
        return this.customerCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomerName() {
        return this.customerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomerPhone() {
        return this.customerPhone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getOrderDate() {
        return this.orderDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getFinalAmount() {
        return this.finalAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<OrderDetailResponse> getItems() {
        return this.items;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPaymentStatus() {
        return this.paymentStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderId(final Long orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerId(final Long customerId) {
        this.customerId = customerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerCode(final String customerCode) {
        this.customerCode = customerCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerName(final String customerName) {
        this.customerName = customerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerPhone(final String customerPhone) {
        this.customerPhone = customerPhone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderDate(final LocalDateTime orderDate) {
        this.orderDate = orderDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalAmount(final BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiscountAmount(final BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFinalAmount(final BigDecimal finalAmount) {
        this.finalAmount = finalAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setItems(final List<OrderDetailResponse> items) {
        this.items = items;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPaymentStatus(final String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPaymentMethod(final String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public List<ServiceItemResponse> getServiceItems() {
        return this.serviceItems;
    }

    public void setServiceItems(final List<ServiceItemResponse> serviceItems) {
        this.serviceItems = serviceItems;
    }
}