// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;

public class OrderItemRequest {
    @NotNull(message = "ProductID không được trống")
    private Long productId;
    @NotNull(message = "Số lượng không được trống")
    @Min(value = 1, message = "Số lượng phải lớn hơn 0")
    private Integer quantity;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getProductId() {
        return this.productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProductId(final Long productId) {
        this.productId = productId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }
}
