// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

public class PetResponse {
	private Long id;
	private Long customerId;
	private String customerCode;
	private String name;
	private String species;
	private String breed;
	private String gender;
	private LocalDate birthDate;
	private BigDecimal weight;
	private Boolean isActive;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public PetResponse() {
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getCustomerId() {
		return this.customerId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCustomerCode() {
		return this.customerCode;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getSpecies() {
		return this.species;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getBreed() {
		return this.breed;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getGender() {
		return this.gender;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDate getBirthDate() {
		return this.birthDate;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public BigDecimal getWeight() {
		return this.weight;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Boolean getIsActive() {
		return this.isActive;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setId(final Long id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCustomerId(final Long customerId) {
		this.customerId = customerId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCustomerCode(final String customerCode) {
		this.customerCode = customerCode;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setName(final String name) {
		this.name = name;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setSpecies(final String species) {
		this.species = species;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setBreed(final String breed) {
		this.breed = breed;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setGender(final String gender) {
		this.gender = gender;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setBirthDate(final LocalDate birthDate) {
		this.birthDate = birthDate;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setWeight(final BigDecimal weight) {
		this.weight = weight;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setIsActive(final Boolean isActive) {
		this.isActive = isActive;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof PetResponse)) return false;
		final PetResponse other = (PetResponse) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$customerId = this.getCustomerId();
		final java.lang.Object other$customerId = other.getCustomerId();
		if (this$customerId == null ? other$customerId != null : !this$customerId.equals(other$customerId)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final java.lang.Object this$species = this.getSpecies();
		final java.lang.Object other$species = other.getSpecies();
		if (this$species == null ? other$species != null : !this$species.equals(other$species)) return false;
		final java.lang.Object this$breed = this.getBreed();
		final java.lang.Object other$breed = other.getBreed();
		if (this$breed == null ? other$breed != null : !this$breed.equals(other$breed)) return false;
		final java.lang.Object this$gender = this.getGender();
		final java.lang.Object other$gender = other.getGender();
		if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
		final java.lang.Object this$birthDate = this.getBirthDate();
		final java.lang.Object other$birthDate = other.getBirthDate();
		if (this$birthDate == null ? other$birthDate != null : !this$birthDate.equals(other$birthDate)) return false;
		final java.lang.Object this$weight = this.getWeight();
		final java.lang.Object other$weight = other.getWeight();
		if (this$weight == null ? other$weight != null : !this$weight.equals(other$weight)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof PetResponse;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $customerId = this.getCustomerId();
		result = result * PRIME + ($customerId == null ? 43 : $customerId.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final java.lang.Object $species = this.getSpecies();
		result = result * PRIME + ($species == null ? 43 : $species.hashCode());
		final java.lang.Object $breed = this.getBreed();
		result = result * PRIME + ($breed == null ? 43 : $breed.hashCode());
		final java.lang.Object $gender = this.getGender();
		result = result * PRIME + ($gender == null ? 43 : $gender.hashCode());
		final java.lang.Object $birthDate = this.getBirthDate();
		result = result * PRIME + ($birthDate == null ? 43 : $birthDate.hashCode());
		final java.lang.Object $weight = this.getWeight();
		result = result * PRIME + ($weight == null ? 43 : $weight.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "PetResponse(id=" + this.getId() + ", customerId=" + this.getCustomerId() + ", name=" + this.getName() + ", species=" + this.getSpecies() + ", breed=" + this.getBreed() + ", gender=" + this.getGender() + ", birthDate=" + this.getBirthDate() + ", weight=" + this.getWeight() + ")";
	}
}
