// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.model;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "Customers")
public class Customer {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CustomerID")
    private Long id;
    @Column(name = "UserID")
    private Long userId;
    @Column(name = "CustomerCode", nullable = true, unique = true)
    private String customerCode;
    @Column(name = "FullName", nullable = false)
    private String fullName;
    @Column(name = "Phone")
    private String phone;
    @Column(name = "Email")
    private String email;
    @Column(name = "Address")
    private String address;
    @Column(name = "BirthDate")
    private LocalDate birthDate;
    @Column(name = "LoyaltyPoints")
    private Integer loyaltyPoints = 0;
    @Column(name = "Tier")
    private String tier = "BRONZE";
    @Column(name = "IsActive")
    private Boolean isActive = true;
    @Column(name = "CreatedAt", updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();
    @Column(name = "UpdatedAt")
    private LocalDateTime updatedAt = LocalDateTime.now();

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomerCode() {
        return this.customerCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getBirthDate() {
        return this.birthDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getLoyaltyPoints() {
        return this.loyaltyPoints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTier() {
        return this.tier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsActive() {
        return this.isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerCode(final String customerCode) {
        this.customerCode = customerCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBirthDate(final LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLoyaltyPoints(final Integer loyaltyPoints) {
        this.loyaltyPoints = loyaltyPoints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTier(final String tier) {
        this.tier = tier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsActive(final Boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
