// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.LocalTime;

@Entity
@Table(name = "Bookings")
public class Booking {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "BookingID")
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CustomerID", nullable = false)
    private Customer customer;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PetID", nullable = false)
    private Pet pet;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ServiceID", nullable = false)
    private Service service;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EmployeeID")
    private Employee employee;
    @Column(name = "BookingDate", nullable = false)
    private LocalDateTime bookingDate;
    // Keep API compatibility even when the current SQL Server schema has not added BookingTime yet.
    @Transient
    private LocalTime bookingTime;
    @Column(name = "Status", nullable = false)
    private String status = "Pending";
    @Column(name = "TotalPrice", nullable = false)
    private BigDecimal totalPrice = BigDecimal.ZERO;
    @Column(name = "Notes")
    private String notes;
    // Current SQL Server schema in use may not have this column yet.
    @Transient
    private String cancellationReason;
    @Column(name = "CreatedAt", updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();
    @Column(name = "UpdatedAt")
    private LocalDateTime updatedAt = LocalDateTime.now();

    public LocalTime getBookingTime() {
        if (bookingTime != null) {
            return bookingTime;
        }
        return bookingDate != null ? bookingDate.toLocalTime() : null;
    }

    public void setBookingTime(LocalTime bookingTime) {
        this.bookingTime = bookingTime;
        if (bookingDate != null && bookingTime != null) {
            this.bookingDate = LocalDateTime.of(bookingDate.toLocalDate(), bookingTime);
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Customer getCustomer() {
        return this.customer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Pet getPet() {
        return this.pet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Service getService() {
        return this.service;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Employee getEmployee() {
        return this.employee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getBookingDate() {
        return this.bookingDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCancellationReason() {
        return this.cancellationReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomer(final Customer customer) {
        this.customer = customer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPet(final Pet pet) {
        this.pet = pet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setService(final Service service) {
        this.service = service;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmployee(final Employee employee) {
        this.employee = employee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBookingDate(final LocalDateTime bookingDate) {
        this.bookingDate = bookingDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalPrice(final BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCancellationReason(final String cancellationReason) {
        this.cancellationReason = cancellationReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
