// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "OrderDetails")
public class OrderDetail {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "OrderDetailID")
    private Long id;
    // Liên kết tới Order
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OrderID", nullable = false)
    private Order order;
    // Liên kết tới Product
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ProductID", nullable = false)
    private Product product;
    @Column(name = "Quantity", nullable = false)
    private Integer quantity;
    @Column(name = "UnitPrice", nullable = false)
    private BigDecimal unitPrice;
    // Subtotal là computed column trong DB (Quantity * UnitPrice), 
    // JPA chỉ đọc, không insert/update
    @Column(name = "Subtotal", insertable = false, updatable = false)
    private BigDecimal subtotal;
    @Column(name = "CreatedAt", updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Order getOrder() {
        return this.order;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrder(final Order order) {
        this.order = order;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProduct(final Product product) {
        this.product = product;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUnitPrice(final BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubtotal(final BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
