// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "Pets")
public class Pet {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PetID")
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CustomerID", nullable = false)
    private Customer customer;
    @Column(name = "PetName", nullable = false)
    private String name;
    @Column(name = "Species")
    private String species = "DOG";
    @Column(name = "Breed")
    private String breed;
    @Column(name = "Gender")
    private String gender;

    @PrePersist
    @PreUpdate
    private void normalizeGender() {
        if (this.gender == null) return;
        this.gender = switch (this.gender.trim().toUpperCase()) {
            case "MALE", "NAM", "ĐỰC", "M" -> "Male";
            case "FEMALE", "NỮ", "CÁI", "F" -> "Female";
            default -> "Unknown";
        };
    }

    @Column(name = "BirthDate")
    private LocalDate birthDate;
    @Column(name = "Weight")
    private BigDecimal weight;
    @Column(name = "Color")
    private String color;
    @Column(name = "HealthNotes")
    private String healthNotes;
    @Column(name = "IsActive")
    private Boolean isActive = true;
    @Column(name = "CreatedAt", updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();
    @Column(name = "UpdatedAt")
    private LocalDateTime updatedAt = LocalDateTime.now();

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Customer getCustomer() {
        return this.customer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSpecies() {
        return this.species;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBreed() {
        return this.breed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGender() {
        return this.gender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getBirthDate() {
        return this.birthDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getWeight() {
        return this.weight;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getColor() {
        return this.color;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHealthNotes() {
        return this.healthNotes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsActive() {
        return this.isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomer(final Customer customer) {
        this.customer = customer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecies(final String species) {
        this.species = species;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBreed(final String breed) {
        this.breed = breed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGender(final String gender) {
        this.gender = gender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBirthDate(final LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeight(final BigDecimal weight) {
        this.weight = weight;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setColor(final String color) {
        this.color = color;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHealthNotes(final String healthNotes) {
        this.healthNotes = healthNotes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsActive(final Boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
