// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "Products")
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ProductID")
    private Long id;
    @Column(name = "CategoryID")
    private Long categoryId;
    @Column(name = "ProductName", nullable = false)
    private String productName;
    @Column(name = "Description")
    private String description;
    @Column(name = "Price", nullable = false)
    private BigDecimal price;
    @Column(name = "StockQuantity", nullable = false)
    private Integer stockQuantity = 0;
    @Column(name = "Unit")
    private String unit = "cái";
    @Column(name = "ImageURL")
    private String imageUrl;
    @Column(name = "IsActive")
    private Boolean isActive = true;
    @Column(name = "CreatedAt", updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();
    @Column(name = "UpdatedAt")
    private LocalDateTime updatedAt = LocalDateTime.now();

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getProductName() {
        return this.productName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStockQuantity() {
        return this.stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUnit() {
        return this.unit;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsActive() {
        return this.isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryId(final Long categoryId) {
        this.categoryId = categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProductName(final String productName) {
        this.productName = productName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrice(final BigDecimal price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStockQuantity(final Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUnit(final String unit) {
        this.unit = unit;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsActive(final Boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
    // ✅ Lombok @Getter tự sinh getIsActive() đúng — KHÔNG viết tay
    // Viết tay ghi đè Lombok → luôn return false → toàn bộ product bị block!
}
