// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

@Entity
@Table(name = "schedules")
public class Schedule {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // ✅ DB dùng camelCase "employeeId" (không phải "employee_id")
    @Column(name = "employeeId", nullable = false)
    private Long employeeId;
    // ✅ DB có cột employeeName riêng — lưu thẳng để tránh JOIN
    @Column(name = "employeeName", length = 200)
    private String employeeName;
    @Column(name = "workDate", nullable = false)
    private LocalDate workDate;
    @Column(name = "shiftStart", nullable = false)
    private LocalTime shiftStart;
    @Column(name = "shiftEnd", nullable = false)
    private LocalTime shiftEnd;
    @Column(length = 500)
    private String notes;
    @Column(name = "createdAt", updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "updatedAt")
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static LocalDateTime $default$createdAt() {
        return LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static LocalDateTime $default$updatedAt() {
        return LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ScheduleBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long employeeId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String employeeName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDate workDate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalTime shiftStart;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalTime shiftEnd;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String notes;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean createdAt$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean updatedAt$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime updatedAt$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ScheduleBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder employeeId(final Long employeeId) {
            this.employeeId = employeeId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder employeeName(final String employeeName) {
            this.employeeName = employeeName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder workDate(final LocalDate workDate) {
            this.workDate = workDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder shiftStart(final LocalTime shiftStart) {
            this.shiftStart = shiftStart;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder shiftEnd(final LocalTime shiftEnd) {
            this.shiftEnd = shiftEnd;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt$value = createdAt;
            createdAt$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule.ScheduleBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt$value = updatedAt;
            updatedAt$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Schedule build() {
            LocalDateTime createdAt$value = this.createdAt$value;
            if (!this.createdAt$set) createdAt$value = Schedule.$default$createdAt();
            LocalDateTime updatedAt$value = this.updatedAt$value;
            if (!this.updatedAt$set) updatedAt$value = Schedule.$default$updatedAt();
            return new Schedule(this.id, this.employeeId, this.employeeName, this.workDate, this.shiftStart, this.shiftEnd, this.notes, createdAt$value, updatedAt$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Schedule.ScheduleBuilder(id=" + this.id + ", employeeId=" + this.employeeId + ", employeeName=" + this.employeeName + ", workDate=" + this.workDate + ", shiftStart=" + this.shiftStart + ", shiftEnd=" + this.shiftEnd + ", notes=" + this.notes + ", createdAt$value=" + this.createdAt$value + ", updatedAt$value=" + this.updatedAt$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Schedule.ScheduleBuilder builder() {
        return new Schedule.ScheduleBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getEmployeeId() {
        return this.employeeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmployeeName() {
        return this.employeeName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getWorkDate() {
        return this.workDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalTime getShiftStart() {
        return this.shiftStart;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalTime getShiftEnd() {
        return this.shiftEnd;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmployeeId(final Long employeeId) {
        this.employeeId = employeeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmployeeName(final String employeeName) {
        this.employeeName = employeeName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWorkDate(final LocalDate workDate) {
        this.workDate = workDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setShiftStart(final LocalTime shiftStart) {
        this.shiftStart = shiftStart;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setShiftEnd(final LocalTime shiftEnd) {
        this.shiftEnd = shiftEnd;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Schedule)) return false;
        final Schedule other = (Schedule) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$employeeId = this.getEmployeeId();
        final java.lang.Object other$employeeId = other.getEmployeeId();
        if (this$employeeId == null ? other$employeeId != null : !this$employeeId.equals(other$employeeId)) return false;
        final java.lang.Object this$employeeName = this.getEmployeeName();
        final java.lang.Object other$employeeName = other.getEmployeeName();
        if (this$employeeName == null ? other$employeeName != null : !this$employeeName.equals(other$employeeName)) return false;
        final java.lang.Object this$workDate = this.getWorkDate();
        final java.lang.Object other$workDate = other.getWorkDate();
        if (this$workDate == null ? other$workDate != null : !this$workDate.equals(other$workDate)) return false;
        final java.lang.Object this$shiftStart = this.getShiftStart();
        final java.lang.Object other$shiftStart = other.getShiftStart();
        if (this$shiftStart == null ? other$shiftStart != null : !this$shiftStart.equals(other$shiftStart)) return false;
        final java.lang.Object this$shiftEnd = this.getShiftEnd();
        final java.lang.Object other$shiftEnd = other.getShiftEnd();
        if (this$shiftEnd == null ? other$shiftEnd != null : !this$shiftEnd.equals(other$shiftEnd)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Schedule;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $employeeId = this.getEmployeeId();
        result = result * PRIME + ($employeeId == null ? 43 : $employeeId.hashCode());
        final java.lang.Object $employeeName = this.getEmployeeName();
        result = result * PRIME + ($employeeName == null ? 43 : $employeeName.hashCode());
        final java.lang.Object $workDate = this.getWorkDate();
        result = result * PRIME + ($workDate == null ? 43 : $workDate.hashCode());
        final java.lang.Object $shiftStart = this.getShiftStart();
        result = result * PRIME + ($shiftStart == null ? 43 : $shiftStart.hashCode());
        final java.lang.Object $shiftEnd = this.getShiftEnd();
        result = result * PRIME + ($shiftEnd == null ? 43 : $shiftEnd.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Schedule(id=" + this.getId() + ", employeeId=" + this.getEmployeeId() + ", employeeName=" + this.getEmployeeName() + ", workDate=" + this.getWorkDate() + ", shiftStart=" + this.getShiftStart() + ", shiftEnd=" + this.getShiftEnd() + ", notes=" + this.getNotes() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Schedule() {
        this.createdAt = Schedule.$default$createdAt();
        this.updatedAt = Schedule.$default$updatedAt();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Schedule(final Long id, final Long employeeId, final String employeeName, final LocalDate workDate, final LocalTime shiftStart, final LocalTime shiftEnd, final String notes, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.workDate = workDate;
        this.shiftStart = shiftStart;
        this.shiftEnd = shiftEnd;
        this.notes = notes;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
