// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "Users")
public class User {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "UserID")
	private Integer id;
	@Column(name = "Username", nullable = false, unique = true, length = 100)
	private String username;
	@Column(name = "Email", nullable = false, unique = true, length = 255)
	private String email;
	@Column(name = "PasswordHash", nullable = false)
	private String password;
	@Column(name = "FullName", nullable = false, length = 200)
	private String fullName;
	@Column(name = "Role", nullable = false, length = 20)
	private String role;
	@Column(name = "Status", nullable = false, length = 20)
	private String status;
	@Column(name = "CreatedAt")
	private LocalDateTime createdAt;
	@Column(name = "UpdatedAt")
	private LocalDateTime updatedAt;

	@PrePersist
	public void prePersist() {
		this.createdAt = LocalDateTime.now();
		this.updatedAt = LocalDateTime.now();
	}

	@PreUpdate
	public void preUpdate() {
		this.updatedAt = LocalDateTime.now();
	}

	public Object getCustomerCode() {
		// TODO Auto-generated method stub
		return null;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	private static String $default$role() {
		return "Customer";
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	private static String $default$status() {
		return "Active";
	}


	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public static class UserBuilder {
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private Integer id;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private String username;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private String email;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private String password;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private String fullName;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private boolean role$set;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private String role$value;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private boolean status$set;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private String status$value;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private LocalDateTime createdAt;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private LocalDateTime updatedAt;

		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		UserBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder id(final Integer id) {
			this.id = id;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder username(final String username) {
			this.username = username;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder email(final String email) {
			this.email = email;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder password(final String password) {
			this.password = password;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder fullName(final String fullName) {
			this.fullName = fullName;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder role(final String role) {
			this.role$value = role;
			role$set = true;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder status(final String status) {
			this.status$value = status;
			status$set = true;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder createdAt(final LocalDateTime createdAt) {
			this.createdAt = createdAt;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User.UserBuilder updatedAt(final LocalDateTime updatedAt) {
			this.updatedAt = updatedAt;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public User build() {
			String role$value = this.role$value;
			if (!this.role$set) role$value = User.$default$role();
			String status$value = this.status$value;
			if (!this.status$set) status$value = User.$default$status();
			return new User(this.id, this.username, this.email, this.password, this.fullName, role$value, status$value, this.createdAt, this.updatedAt);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public java.lang.String toString() {
			return "User.UserBuilder(id=" + this.id + ", username=" + this.username + ", email=" + this.email + ", password=" + this.password + ", fullName=" + this.fullName + ", role$value=" + this.role$value + ", status$value=" + this.status$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public static User.UserBuilder builder() {
		return new User.UserBuilder();
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Integer getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUsername() {
		return this.username;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getEmail() {
		return this.email;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPassword() {
		return this.password;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getFullName() {
		return this.fullName;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRole() {
		return this.role;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getStatus() {
		return this.status;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreatedAt() {
		return this.createdAt;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdatedAt() {
		return this.updatedAt;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setId(final Integer id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUsername(final String username) {
		this.username = username;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setEmail(final String email) {
		this.email = email;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPassword(final String password) {
		this.password = password;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setFullName(final String fullName) {
		this.fullName = fullName;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRole(final String role) {
		this.role = role;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setStatus(final String status) {
		this.status = status;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreatedAt(final LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdatedAt(final LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof User)) return false;
		final User other = (User) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$username = this.getUsername();
		final java.lang.Object other$username = other.getUsername();
		if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
		final java.lang.Object this$email = this.getEmail();
		final java.lang.Object other$email = other.getEmail();
		if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
		final java.lang.Object this$password = this.getPassword();
		final java.lang.Object other$password = other.getPassword();
		if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
		final java.lang.Object this$fullName = this.getFullName();
		final java.lang.Object other$fullName = other.getFullName();
		if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
		final java.lang.Object this$role = this.getRole();
		final java.lang.Object other$role = other.getRole();
		if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
		final java.lang.Object this$status = this.getStatus();
		final java.lang.Object other$status = other.getStatus();
		if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
		final java.lang.Object this$createdAt = this.getCreatedAt();
		final java.lang.Object other$createdAt = other.getCreatedAt();
		if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
		final java.lang.Object this$updatedAt = this.getUpdatedAt();
		final java.lang.Object other$updatedAt = other.getUpdatedAt();
		if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof User;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $username = this.getUsername();
		result = result * PRIME + ($username == null ? 43 : $username.hashCode());
		final java.lang.Object $email = this.getEmail();
		result = result * PRIME + ($email == null ? 43 : $email.hashCode());
		final java.lang.Object $password = this.getPassword();
		result = result * PRIME + ($password == null ? 43 : $password.hashCode());
		final java.lang.Object $fullName = this.getFullName();
		result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
		final java.lang.Object $role = this.getRole();
		result = result * PRIME + ($role == null ? 43 : $role.hashCode());
		final java.lang.Object $status = this.getStatus();
		result = result * PRIME + ($status == null ? 43 : $status.hashCode());
		final java.lang.Object $createdAt = this.getCreatedAt();
		result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
		final java.lang.Object $updatedAt = this.getUpdatedAt();
		result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "User(id=" + this.getId() + ", username=" + this.getUsername() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", fullName=" + this.getFullName() + ", role=" + this.getRole() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public User() {
		this.role = User.$default$role();
		this.status = User.$default$status();
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public User(final Integer id, final String username, final String email, final String password, final String fullName, final String role, final String status, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
		this.id = id;
		this.username = username;
		this.email = email;
		this.password = password;
		this.fullName = fullName;
		this.role = role;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}
}
