// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.time.LocalDateTime;
// Bỏ qua field null khi serialize JSON
/**
 * ============================================================
 * ApiResponse - Chuẩn hóa response trả về cho client
 * ============================================================
 * Mọi response từ API đều được bọc trong class này để
 * đảm bảo format nhất quán.
 *
 * @JsonInclude(NON_NULL): Không trả về field null trong JSON
 *
 * Ví dụ response thành công:
 * {
 *   "success": true,
 *   "message": "Đăng nhập thành công",
 *   "data": { "token": "eyJhbGci..." },
 *   "timestamp": "2024-01-01T10:00:00"
 * }
 *
 * Ví dụ response lỗi:
 * {
 *   "success": false,
 *   "message": "Tên đăng nhập đã tồn tại",
 *   "timestamp": "2024-01-01T10:00:00"
 * }
 * ============================================================
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ApiResponse<T> {
   /**
    * true = thành công, false = thất bại
    */
   private boolean success;
   /**
    * Thông báo cho người dùng
    */
   private String message;
   /**
    * Dữ liệu trả về (generic type, có thể là bất kỳ object nào)
    */
   private T data;
   /**
    * Thời điểm response được tạo
    */
   private LocalDateTime timestamp;

   // ========================
   // Factory methods tiện ích
   // ========================
   /**
    * Tạo response thành công có kèm data
    */
   public static <T> ApiResponse<T> success(String message, T data) {
      return ApiResponse.<T>builder().success(true).message(message).data(data).build();
   }

   /**
    * Tạo response thành công không có data
    */
   public static <T> ApiResponse<T> success(String message) {
      return ApiResponse.<T>builder().success(true).message(message).build();
   }

   /**
    * Tạo response thất bại
    */
   public static <T> ApiResponse<T> error(String message) {
      return ApiResponse.<T>builder().success(false).message(message).build();
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   private static <T> LocalDateTime $default$timestamp() {
      return LocalDateTime.now();
   }


   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public static class ApiResponseBuilder<T> {
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      private boolean success;
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      private String message;
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      private T data;
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      private boolean timestamp$set;
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      private LocalDateTime timestamp$value;

      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      ApiResponseBuilder() {
      }

      /**
       * true = thành công, false = thất bại
       * @return {@code this}.
       */
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      public ApiResponse.ApiResponseBuilder<T> success(final boolean success) {
         this.success = success;
         return this;
      }

      /**
       * Thông báo cho người dùng
       * @return {@code this}.
       */
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      public ApiResponse.ApiResponseBuilder<T> message(final String message) {
         this.message = message;
         return this;
      }

      /**
       * Dữ liệu trả về (generic type, có thể là bất kỳ object nào)
       * @return {@code this}.
       */
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      public ApiResponse.ApiResponseBuilder<T> data(final T data) {
         this.data = data;
         return this;
      }

      /**
       * Thời điểm response được tạo
       * @return {@code this}.
       */
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      public ApiResponse.ApiResponseBuilder<T> timestamp(final LocalDateTime timestamp) {
         this.timestamp$value = timestamp;
         timestamp$set = true;
         return this;
      }

      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      public ApiResponse<T> build() {
         LocalDateTime timestamp$value = this.timestamp$value;
         if (!this.timestamp$set) timestamp$value = ApiResponse.<T>$default$timestamp();
         return new ApiResponse<T>(this.success, this.message, this.data, timestamp$value);
      }

      @java.lang.Override
      @java.lang.SuppressWarnings("all")
      @lombok.Generated
      public java.lang.String toString() {
         return "ApiResponse.ApiResponseBuilder(success=" + this.success + ", message=" + this.message + ", data=" + this.data + ", timestamp$value=" + this.timestamp$value + ")";
      }
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public static <T> ApiResponse.ApiResponseBuilder<T> builder() {
      return new ApiResponse.ApiResponseBuilder<T>();
   }

   /**
    * true = thành công, false = thất bại
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public boolean isSuccess() {
      return this.success;
   }

   /**
    * Thông báo cho người dùng
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public String getMessage() {
      return this.message;
   }

   /**
    * Dữ liệu trả về (generic type, có thể là bất kỳ object nào)
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public T getData() {
      return this.data;
   }

   /**
    * Thời điểm response được tạo
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public LocalDateTime getTimestamp() {
      return this.timestamp;
   }

   /**
    * true = thành công, false = thất bại
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public void setSuccess(final boolean success) {
      this.success = success;
   }

   /**
    * Thông báo cho người dùng
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public void setMessage(final String message) {
      this.message = message;
   }

   /**
    * Dữ liệu trả về (generic type, có thể là bất kỳ object nào)
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public void setData(final T data) {
      this.data = data;
   }

   /**
    * Thời điểm response được tạo
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public void setTimestamp(final LocalDateTime timestamp) {
      this.timestamp = timestamp;
   }

   @java.lang.Override
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof ApiResponse)) return false;
      final ApiResponse<?> other = (ApiResponse<?>) o;
      if (!other.canEqual((java.lang.Object) this)) return false;
      if (this.isSuccess() != other.isSuccess()) return false;
      final java.lang.Object this$message = this.getMessage();
      final java.lang.Object other$message = other.getMessage();
      if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
      final java.lang.Object this$data = this.getData();
      final java.lang.Object other$data = other.getData();
      if (this$data == null ? other$data != null : !this$data.equals(other$data)) return false;
      final java.lang.Object this$timestamp = this.getTimestamp();
      final java.lang.Object other$timestamp = other.getTimestamp();
      if (this$timestamp == null ? other$timestamp != null : !this$timestamp.equals(other$timestamp)) return false;
      return true;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   protected boolean canEqual(final java.lang.Object other) {
      return other instanceof ApiResponse;
   }

   @java.lang.Override
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      result = result * PRIME + (this.isSuccess() ? 79 : 97);
      final java.lang.Object $message = this.getMessage();
      result = result * PRIME + ($message == null ? 43 : $message.hashCode());
      final java.lang.Object $data = this.getData();
      result = result * PRIME + ($data == null ? 43 : $data.hashCode());
      final java.lang.Object $timestamp = this.getTimestamp();
      result = result * PRIME + ($timestamp == null ? 43 : $timestamp.hashCode());
      return result;
   }

   @java.lang.Override
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public java.lang.String toString() {
      return "ApiResponse(success=" + this.isSuccess() + ", message=" + this.getMessage() + ", data=" + this.getData() + ", timestamp=" + this.getTimestamp() + ")";
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public ApiResponse() {
      this.timestamp = ApiResponse.$default$timestamp();
   }

   /**
    * Creates a new {@code ApiResponse} instance.
    *
    * @param success true = thành công, false = thất bại
    * @param message Thông báo cho người dùng
    * @param data Dữ liệu trả về (generic type, có thể là bất kỳ object nào)
    * @param timestamp Thời điểm response được tạo
    */
   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public ApiResponse(final boolean success, final String message, final T data, final LocalDateTime timestamp) {
      this.success = success;
      this.message = message;
      this.data = data;
      this.timestamp = timestamp;
   }
}

/**kiet */