// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.time.LocalTime;

public class BookingRequest {
    @NotNull(message = "CustomerID không được trống")
    private Long customerId;
    @NotNull(message = "PetID không được trống")
    private Long petId;
    private Long serviceId;
    // Hỗ trợ chọn nhiều dịch vụ
    private java.util.List<Long> serviceIds;
    // Nhân viên thực hiện — có thể null (phân công sau)
    private Long employeeId;
    @NotNull(message = "Ngày đặt lịch không được trống")
    private LocalDate bookingDate;
    @NotNull(message = "Giờ đặt lịch không được trống")
    private LocalTime bookingTime;
    private String notes;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.util.List<Long> getServiceIds() {
        return this.serviceIds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setServiceIds(final java.util.List<Long> serviceIds) {
        this.serviceIds = serviceIds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCustomerId() {
        return this.customerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getPetId() {
        return this.petId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getServiceId() {
        return this.serviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getEmployeeId() {
        return this.employeeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getBookingDate() {
        return this.bookingDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalTime getBookingTime() {
        return this.bookingTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerId(final Long customerId) {
        this.customerId = customerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPetId(final Long petId) {
        this.petId = petId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setServiceId(final Long serviceId) {
        this.serviceId = serviceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmployeeId(final Long employeeId) {
        this.employeeId = employeeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBookingDate(final LocalDate bookingDate) {
        this.bookingDate = bookingDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBookingTime(final LocalTime bookingTime) {
        this.bookingTime = bookingTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }
}
