// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import java.time.LocalDate;

public class CustomerResponse {
    private Long id;
    private String customerCode;
    private String fullName;
    private String phone;
    private String email;
    private String address;
    private LocalDate birthDate;
    private Integer loyaltyPoints;
    private String tier;
    private Boolean isActive;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CustomerResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomerCode() {
        return this.customerCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getBirthDate() {
        return this.birthDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getLoyaltyPoints() {
        return this.loyaltyPoints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTier() {
        return this.tier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsActive() {
        return this.isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomerCode(final String customerCode) {
        this.customerCode = customerCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBirthDate(final LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLoyaltyPoints(final Integer loyaltyPoints) {
        this.loyaltyPoints = loyaltyPoints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTier(final String tier) {
        this.tier = tier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsActive(final Boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CustomerResponse)) return false;
        final CustomerResponse other = (CustomerResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$loyaltyPoints = this.getLoyaltyPoints();
        final java.lang.Object other$loyaltyPoints = other.getLoyaltyPoints();
        if (this$loyaltyPoints == null ? other$loyaltyPoints != null : !this$loyaltyPoints.equals(other$loyaltyPoints)) return false;
        final java.lang.Object this$isActive = this.getIsActive();
        final java.lang.Object other$isActive = other.getIsActive();
        if (this$isActive == null ? other$isActive != null : !this$isActive.equals(other$isActive)) return false;
        final java.lang.Object this$customerCode = this.getCustomerCode();
        final java.lang.Object other$customerCode = other.getCustomerCode();
        if (this$customerCode == null ? other$customerCode != null : !this$customerCode.equals(other$customerCode)) return false;
        final java.lang.Object this$fullName = this.getFullName();
        final java.lang.Object other$fullName = other.getFullName();
        if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$birthDate = this.getBirthDate();
        final java.lang.Object other$birthDate = other.getBirthDate();
        if (this$birthDate == null ? other$birthDate != null : !this$birthDate.equals(other$birthDate)) return false;
        final java.lang.Object this$tier = this.getTier();
        final java.lang.Object other$tier = other.getTier();
        if (this$tier == null ? other$tier != null : !this$tier.equals(other$tier)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CustomerResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $loyaltyPoints = this.getLoyaltyPoints();
        result = result * PRIME + ($loyaltyPoints == null ? 43 : $loyaltyPoints.hashCode());
        final java.lang.Object $isActive = this.getIsActive();
        result = result * PRIME + ($isActive == null ? 43 : $isActive.hashCode());
        final java.lang.Object $customerCode = this.getCustomerCode();
        result = result * PRIME + ($customerCode == null ? 43 : $customerCode.hashCode());
        final java.lang.Object $fullName = this.getFullName();
        result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $birthDate = this.getBirthDate();
        result = result * PRIME + ($birthDate == null ? 43 : $birthDate.hashCode());
        final java.lang.Object $tier = this.getTier();
        result = result * PRIME + ($tier == null ? 43 : $tier.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CustomerResponse(id=" + this.getId() + ", customerCode=" + this.getCustomerCode() + ", fullName=" + this.getFullName() + ", phone=" + this.getPhone() + ", email=" + this.getEmail() + ", address=" + this.getAddress() + ", birthDate=" + this.getBirthDate() + ", loyaltyPoints=" + this.getLoyaltyPoints() + ", tier=" + this.getTier() + ", isActive=" + this.getIsActive() + ")";
    }
}
