// Generated by delombok at Sat May 09 00:02:16 GMT+07:00 2026
package com.petshop.backend.dto;

import jakarta.validation.constraints.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalTime;

public class ScheduleDTO {
	private Long id;
	@NotNull(message = "Phải chọn nhân viên")
	private Long employeeId;
	private String employeeName;
	@NotNull(message = "Ngày làm việc không được để trống")
	private LocalDate workDate;
	@NotNull(message = "Giờ bắt đầu không được để trống")
	private LocalTime shiftStart;
	@NotNull(message = "Giờ kết thúc không được để trống")
	private LocalTime shiftEnd;
	private String notes;

	public String getFullName() {
		// TODO Auto-generated method stub
		return null;
	}


	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public static class ScheduleDTOBuilder {
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private Long id;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private Long employeeId;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private String employeeName;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private LocalDate workDate;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private LocalTime shiftStart;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private LocalTime shiftEnd;
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		private String notes;

		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		ScheduleDTOBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public ScheduleDTO.ScheduleDTOBuilder id(final Long id) {
			this.id = id;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public ScheduleDTO.ScheduleDTOBuilder employeeId(final Long employeeId) {
			this.employeeId = employeeId;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public ScheduleDTO.ScheduleDTOBuilder employeeName(final String employeeName) {
			this.employeeName = employeeName;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public ScheduleDTO.ScheduleDTOBuilder workDate(final LocalDate workDate) {
			this.workDate = workDate;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public ScheduleDTO.ScheduleDTOBuilder shiftStart(final LocalTime shiftStart) {
			this.shiftStart = shiftStart;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public ScheduleDTO.ScheduleDTOBuilder shiftEnd(final LocalTime shiftEnd) {
			this.shiftEnd = shiftEnd;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public ScheduleDTO.ScheduleDTOBuilder notes(final String notes) {
			this.notes = notes;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public ScheduleDTO build() {
			return new ScheduleDTO(this.id, this.employeeId, this.employeeName, this.workDate, this.shiftStart, this.shiftEnd, this.notes);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		@lombok.Generated
		public java.lang.String toString() {
			return "ScheduleDTO.ScheduleDTOBuilder(id=" + this.id + ", employeeId=" + this.employeeId + ", employeeName=" + this.employeeName + ", workDate=" + this.workDate + ", shiftStart=" + this.shiftStart + ", shiftEnd=" + this.shiftEnd + ", notes=" + this.notes + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public static ScheduleDTO.ScheduleDTOBuilder builder() {
		return new ScheduleDTO.ScheduleDTOBuilder();
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getEmployeeId() {
		return this.employeeId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getEmployeeName() {
		return this.employeeName;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDate getWorkDate() {
		return this.workDate;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalTime getShiftStart() {
		return this.shiftStart;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalTime getShiftEnd() {
		return this.shiftEnd;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getNotes() {
		return this.notes;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setId(final Long id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setEmployeeId(final Long employeeId) {
		this.employeeId = employeeId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setEmployeeName(final String employeeName) {
		this.employeeName = employeeName;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setWorkDate(final LocalDate workDate) {
		this.workDate = workDate;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setShiftStart(final LocalTime shiftStart) {
		this.shiftStart = shiftStart;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setShiftEnd(final LocalTime shiftEnd) {
		this.shiftEnd = shiftEnd;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setNotes(final String notes) {
		this.notes = notes;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ScheduleDTO)) return false;
		final ScheduleDTO other = (ScheduleDTO) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$employeeId = this.getEmployeeId();
		final java.lang.Object other$employeeId = other.getEmployeeId();
		if (this$employeeId == null ? other$employeeId != null : !this$employeeId.equals(other$employeeId)) return false;
		final java.lang.Object this$employeeName = this.getEmployeeName();
		final java.lang.Object other$employeeName = other.getEmployeeName();
		if (this$employeeName == null ? other$employeeName != null : !this$employeeName.equals(other$employeeName)) return false;
		final java.lang.Object this$workDate = this.getWorkDate();
		final java.lang.Object other$workDate = other.getWorkDate();
		if (this$workDate == null ? other$workDate != null : !this$workDate.equals(other$workDate)) return false;
		final java.lang.Object this$shiftStart = this.getShiftStart();
		final java.lang.Object other$shiftStart = other.getShiftStart();
		if (this$shiftStart == null ? other$shiftStart != null : !this$shiftStart.equals(other$shiftStart)) return false;
		final java.lang.Object this$shiftEnd = this.getShiftEnd();
		final java.lang.Object other$shiftEnd = other.getShiftEnd();
		if (this$shiftEnd == null ? other$shiftEnd != null : !this$shiftEnd.equals(other$shiftEnd)) return false;
		final java.lang.Object this$notes = this.getNotes();
		final java.lang.Object other$notes = other.getNotes();
		if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof ScheduleDTO;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $employeeId = this.getEmployeeId();
		result = result * PRIME + ($employeeId == null ? 43 : $employeeId.hashCode());
		final java.lang.Object $employeeName = this.getEmployeeName();
		result = result * PRIME + ($employeeName == null ? 43 : $employeeName.hashCode());
		final java.lang.Object $workDate = this.getWorkDate();
		result = result * PRIME + ($workDate == null ? 43 : $workDate.hashCode());
		final java.lang.Object $shiftStart = this.getShiftStart();
		result = result * PRIME + ($shiftStart == null ? 43 : $shiftStart.hashCode());
		final java.lang.Object $shiftEnd = this.getShiftEnd();
		result = result * PRIME + ($shiftEnd == null ? 43 : $shiftEnd.hashCode());
		final java.lang.Object $notes = this.getNotes();
		result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "ScheduleDTO(id=" + this.getId() + ", employeeId=" + this.getEmployeeId() + ", employeeName=" + this.getEmployeeName() + ", workDate=" + this.getWorkDate() + ", shiftStart=" + this.getShiftStart() + ", shiftEnd=" + this.getShiftEnd() + ", notes=" + this.getNotes() + ")";
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public ScheduleDTO() {
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public ScheduleDTO(final Long id, final Long employeeId, final String employeeName, final LocalDate workDate, final LocalTime shiftStart, final LocalTime shiftEnd, final String notes) {
		this.id = id;
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.workDate = workDate;
		this.shiftStart = shiftStart;
		this.shiftEnd = shiftEnd;
		this.notes = notes;
	}
}
